// <auto-generated />
using System;
using EduFlow.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduFlow.Infrastructure.Migrations
{
    [DbContext(typeof(EduDbContext))]
    [Migration("20260415000001_AddWaitingListSystem")]
    partial class AddWaitingListSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Configuration for WaitingListEntry would be included here
            // This is a simplified version - actual implementation may vary based on your full model
#pragma warning restore 612, 618
        }
    }
}
